/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hadiahnomer2kalkulator;

/**
 *
 * @author USER
 */
public class Kalkulator extends javax.swing.JFrame {
        String angka;
        double hasil, angka1, angka2;
        int pilih;
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Display = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buttonplus = new javax.swing.JButton();
        buttonkurang = new javax.swing.JButton();
        buttonkali = new javax.swing.JButton();
        buttonbagi = new javax.swing.JButton();
        Buttonnomer1 = new javax.swing.JButton();
        Buttonnomer0 = new javax.swing.JButton();
        Buttonnomer2 = new javax.swing.JButton();
        Buttonnomer3 = new javax.swing.JButton();
        Buttonnomer4 = new javax.swing.JButton();
        Buttonnomer5 = new javax.swing.JButton();
        Buttonnomer6 = new javax.swing.JButton();
        Buttonnomer7 = new javax.swing.JButton();
        Buttonnomer8 = new javax.swing.JButton();
        Buttonkoma = new javax.swing.JButton();
        Buttonnomer9 = new javax.swing.JButton();
        buttonhasil = new javax.swing.JButton();
        buttonpersen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dekstop Kalkulator");

        Display.setEditable(false);
        Display.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        jButton1.setText("C");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonplus.setText("+");
        buttonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonplusActionPerformed(evt);
            }
        });

        buttonkurang.setText("-");
        buttonkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkurangActionPerformed(evt);
            }
        });

        buttonkali.setText("*");
        buttonkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonkaliActionPerformed(evt);
            }
        });

        buttonbagi.setText("/");
        buttonbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonbagiActionPerformed(evt);
            }
        });

        Buttonnomer1.setText("1");
        Buttonnomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer1ActionPerformed(evt);
            }
        });

        Buttonnomer0.setText("0");
        Buttonnomer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer0ActionPerformed(evt);
            }
        });

        Buttonnomer2.setText("2");
        Buttonnomer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer2ActionPerformed(evt);
            }
        });

        Buttonnomer3.setText("3");
        Buttonnomer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer3ActionPerformed(evt);
            }
        });

        Buttonnomer4.setText("4");
        Buttonnomer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer4ActionPerformed(evt);
            }
        });

        Buttonnomer5.setText("5");
        Buttonnomer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer5ActionPerformed(evt);
            }
        });

        Buttonnomer6.setText("6");
        Buttonnomer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer6ActionPerformed(evt);
            }
        });

        Buttonnomer7.setText("7");
        Buttonnomer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer7ActionPerformed(evt);
            }
        });

        Buttonnomer8.setText("8");
        Buttonnomer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer8ActionPerformed(evt);
            }
        });

        Buttonkoma.setText(",");
        Buttonkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonkomaActionPerformed(evt);
            }
        });

        Buttonnomer9.setText("9");
        Buttonnomer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnomer9ActionPerformed(evt);
            }
        });

        buttonhasil.setText("Hasil");
        buttonhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonhasilActionPerformed(evt);
            }
        });

        buttonpersen.setText("%");
        buttonpersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonpersenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(buttonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Buttonnomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buttonnomer4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(Buttonnomer7, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(Buttonnomer0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Buttonnomer2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(Buttonnomer5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(Buttonnomer8, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(buttonpersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Buttonnomer3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonnomer6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonnomer9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonkali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buttonbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(buttonplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonbagi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonkali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buttonnomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buttonnomer4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buttonnomer8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnomer9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonpersen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Buttonnomer0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Buttonkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(buttonhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Buttonnomer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer2ActionPerformed
        angka += "2";
        Display.setText(angka);        
    }//GEN-LAST:event_Buttonnomer2ActionPerformed

    private void Buttonnomer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer4ActionPerformed
        angka += "4";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer4ActionPerformed

    private void Buttonnomer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer5ActionPerformed
         angka += "5";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer5ActionPerformed

    private void Buttonnomer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer6ActionPerformed
         angka += "6";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer6ActionPerformed

    private void Buttonnomer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer0ActionPerformed
         angka += "0";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer0ActionPerformed

    private void ButtonkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonkomaActionPerformed
         angka += ".";
        Display.setText(angka);
    }//GEN-LAST:event_ButtonkomaActionPerformed

    private void Buttonnomer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer9ActionPerformed
         angka += "9";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer9ActionPerformed

    private void Buttonnomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer1ActionPerformed
        angka += "1";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer1ActionPerformed

    private void Buttonnomer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer3ActionPerformed
         angka += "3";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer3ActionPerformed

    private void Buttonnomer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer7ActionPerformed
         angka += "7";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer7ActionPerformed

    private void Buttonnomer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnomer8ActionPerformed
         angka += "8";
        Display.setText(angka);
    }//GEN-LAST:event_Buttonnomer8ActionPerformed

    private void buttonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonplusActionPerformed
        angka1 = Double.parseDouble(angka);
        Display.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_buttonplusActionPerformed

    private void buttonkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkurangActionPerformed
         angka1 = Double.parseDouble(angka);
        Display.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_buttonkurangActionPerformed

    private void buttonkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonkaliActionPerformed
         angka1 = Double.parseDouble(angka);
        Display.setText("*");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_buttonkaliActionPerformed

    private void buttonbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonbagiActionPerformed
         angka1 = Double.parseDouble(angka);
        Display.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_buttonbagiActionPerformed

    private void buttonhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonhasilActionPerformed
       switch (pilih){
         case 1 :
            angka2 = Double.parseDouble(angka);
            hasil = angka1 + angka2;
            angka = Double.toString(hasil);
            Display.setText(angka);
            break;
        case 2 :
         angka2 = Double.parseDouble(angka);
            hasil = angka1 - angka2;
            angka = Double.toString(hasil);
            Display.setText(angka);
            break;
        case 3 :
         angka2 = Double.parseDouble(angka);
            hasil = angka1 * angka2;
            angka = Double.toString(hasil);
            Display.setText(angka);
            break;
        case 4 :
         angka2 = Double.parseDouble(angka);
            hasil = angka1 / angka2;
            angka = Double.toString(hasil);
            Display.setText(angka);
            break;
        case 5 :
            angka2 = Double.parseDouble(angka);
            hasil = angka1 % angka2;
            angka = Double.toString(hasil);
            Display.setText(angka);
            break;
        default:
            break;
   
            
        
        
            
            
    }
    }//GEN-LAST:event_buttonhasilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Display.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        hasil = 0.0;
        angka = "";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonpersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonpersenActionPerformed
        angka1 = Double.parseDouble(angka);
        Display.setText("%");
        angka = "";
        pilih = 5;
    }//GEN-LAST:event_buttonpersenActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kalkulator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonkoma;
    private javax.swing.JButton Buttonnomer0;
    private javax.swing.JButton Buttonnomer1;
    private javax.swing.JButton Buttonnomer2;
    private javax.swing.JButton Buttonnomer3;
    private javax.swing.JButton Buttonnomer4;
    private javax.swing.JButton Buttonnomer5;
    private javax.swing.JButton Buttonnomer6;
    private javax.swing.JButton Buttonnomer7;
    private javax.swing.JButton Buttonnomer8;
    private javax.swing.JButton Buttonnomer9;
    private javax.swing.JTextField Display;
    private javax.swing.JButton buttonbagi;
    private javax.swing.JButton buttonhasil;
    private javax.swing.JButton buttonkali;
    private javax.swing.JButton buttonkurang;
    private javax.swing.JButton buttonpersen;
    private javax.swing.JButton buttonplus;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
